In [ ]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]
sys.path.append(str(PROJECT_ROOT))

import pandas as pd
from src.utils.db import get_engine

engine = get_engine()

#### 데이터 불러오기

In [ ]:
import pandas as pd

base_path = r"C:\Users\wjdtm\OneDrive\바탕 화면\CODEIT DA\Codeit DA Part.4 (2026.08.03 ~ 2026.10.02)\데이터 분석 고급 프로젝트\DATA_CSV"

# 10만 건씩 나누어서 읽은 뒤 리스트에 담아 합치기
chunk_size = 100000
chunks = []

for chunk in pd.read_csv(f"{base_path}\\accounts_friendrequest.csv", sep='\t', encoding='utf-8', chunksize=chunk_size):
    chunks.append(chunk)

df_friendrequest = pd.concat(chunks, ignore_index=True)

# 나머지 파일들은 용량이 작다면 그대로 로드
df_contacts = pd.read_csv(f"{base_path}\\accounts_user_contacts.csv", encoding='utf-8')
df_payment = pd.read_csv(f"{base_path}\\accounts_paymenthistory.csv", encoding='utf-8')

In [ ]:
# df_friendrequest 잘 불러왔는지 확인
df_friendrequest.head()

,id,status,created_at,updated_at,receive_user_id,send_user_id
0,7,P,2023-04-17 18:29:11,2023-04-17 18:29:11,831962,837521
1,10,A,2023-04-17 18:29:11,2023-04-22 06:02:53,832151,837521
2,11,A,2023-04-17 18:29:11,2023-04-18 19:28:41,832340,837521
3,13,A,2023-04-17 18:29:11,2023-04-19 11:05:04,833041,837521
4,20,P,2023-04-17 18:29:11,2023-04-17 18:29:11,834415,837521

In [ ]:
df_friendrequest.info()

<class 'pandas.DataFrame'>
RangeIndex: 17147175 entries, 0 to 17147174
Data columns (total 6 columns):
 #   Column           Dtype
---  ------           -----
 0   id               int64
 1   status           str
 2   created_at       str
 3   updated_at       str
 4   receive_user_id  int64
 5   send_user_id     int64
dtypes: int64(3), str(3)
memory usage: 784.9 MB

In [ ]:
# 날짜 컬럼 'created_at', 'updated_at' 데이터 타입 datetime으로 변경, id 컬럼 'id', 'user_id' 데이터 타입 object로 변경
df_friendrequest['created_at'] = pd.to_datetime(df_friendrequest['created_at'], errors='coerce')
df_friendrequest['updated_at'] = pd.to_datetime(df_friendrequest['updated_at'], errors='coerce')
df_friendrequest['id'] = df_friendrequest['id'].astype(object)
df_friendrequest['user_id'] = df_friendrequest['send_user_id'].astype(object)

# 변환 후 정보 확인
df_friendrequest.info()

<class 'pandas.DataFrame'>
RangeIndex: 17147175 entries, 0 to 17147174
Data columns (total 7 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   status           str
 2   created_at       datetime64[us]
 3   updated_at       datetime64[us]
 4   receive_user_id  int64
 5   send_user_id     int64
 6   user_id          object
dtypes: datetime64[us](2), int64(2), object(2), str(1)
memory usage: 915.8+ MB

In [ ]:
# df_contacts 잘 불러왔는지 확인
df_contacts.head()

      id  contacts_count invite_user_id_list  user_id
0    259              30                  []  1167696
1   1756              79                  []   863169
2  13742              21            [854615]   857205
3  13754              29                  []   851431
4  13756              28            [849318]   855476

In [ ]:
df_contacts.info()

<class 'pandas.DataFrame'>
RangeIndex: 5063 entries, 0 to 5062
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   5063 non-null   int64
 1   contacts_count       5063 non-null   int64
 2   invite_user_id_list  5063 non-null   str
 3   user_id              5063 non-null   int64
dtypes: int64(3), str(1)
memory usage: 158.3 KB

In [ ]:
# id 컬럼 'id', 'user_id' 데이터 타입 object로 변경
df_contacts['id'] = df_contacts['id'].astype(object)
df_contacts['user_id'] = df_contacts['user_id'].astype(object)

# 변환 후 정보 확인
df_contacts.info()

<class 'pandas.DataFrame'>
RangeIndex: 5063 entries, 0 to 5062
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   5063 non-null   object
 1   contacts_count       5063 non-null   int64
 2   invite_user_id_list  5063 non-null   str
 3   user_id              5063 non-null   object
dtypes: int64(1), object(2), str(1)
memory usage: 158.3+ KB

In [ ]:
# df_payment 잘 불러왔는지 확인
df_payment.head()

   id  productId phone_type           created_at  user_id
0   6  heart.777          A  2023-05-13 21:28:34  1211127
1   7  heart.777          A  2023-05-13 21:29:39  1151343
2   8  heart.777          A  2023-05-13 21:31:33  1002147
3   9  heart.777          A  2023-05-13 21:31:39  1095040
4  11  heart.777          A  2023-05-13 21:34:32  1164081

In [ ]:
df_payment.info()

<class 'pandas.DataFrame'>
RangeIndex: 95140 entries, 0 to 95139
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          95140 non-null  int64
 1   productId   95140 non-null  str
 2   phone_type  95140 non-null  str
 3   created_at  95140 non-null  str
 4   user_id     95140 non-null  int64
dtypes: int64(2), str(3)
memory usage: 3.6 MB

In [ ]:
# id 컬럼 'id', 'user_id' 데이터 타입 object로 변경, 날짜컬럼 'created_at' 데이터 타입 datetime으로 변경
df_payment['id'] = df_payment['id'].astype(object)
df_payment['user_id'] = df_payment['user_id'].astype(object)
df_payment['created_at'] = pd.to_datetime(df_payment['created_at'], errors='coerce')

# 변환 후 정보 확인
df_payment.info()

<class 'pandas.DataFrame'>
RangeIndex: 95140 entries, 0 to 95139
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          95140 non-null  object
 1   productId   95140 non-null  str
 2   phone_type  95140 non-null  str
 3   created_at  95140 non-null  datetime64[us]
 4   user_id     95140 non-null  object
dtypes: datetime64[us](1), object(2), str(2)
memory usage: 3.6+ MB

#### 각 파일별 중복값 확인하기

In [ ]:
# df_friendrequest 중복값 확인
df_friendrequest.duplicated().sum()

np.int64(0)

In [ ]:
# df_contacts 중복값 확인
df_contacts.duplicated().sum()

np.int64(0)

In [ ]:
# df_payment 중복값 확인
df_payment.duplicated().sum()

np.int64(0)

#### 각 파일별 결측값 확인하기

In [ ]:
# df_friendrequest 결측값 확인
df_friendrequest.isnull().sum()

id                 0
status             0
created_at         0
updated_at         0
receive_user_id    0
send_user_id       0
user_id            0
dtype: int64

In [ ]:
# df_contacts 결측값 확인
df_contacts.isnull().sum()

id                     0
contacts_count         0
invite_user_id_list    0
user_id                0
dtype: int64

In [ ]:
# df_payment 결측값 확인
df_payment.isnull().sum()

id            0
productId     0
phone_type    0
created_at    0
user_id       0
dtype: int64

#### 각 파일별 이상치 확인하기

In [ ]:
# df_friendrequest 이상치 확인
df_friendrequest.describe()

,created_at,updated_at,receive_user_id,send_user_id
count,17147175,17147175,1.714718e+07,1.714718e+07
mean,2023-05-17 19:14:14.416624,2023-05-19 03:18:26.881183,1.154812e+06,1.215895e+06
min,2023-04-17 18:29:11,2023-04-17 18:29:11,8.319620e+05,8.319620e+05
25%,2023-05-10 10:53:21,2023-05-11 03:51:13,9.737080e+05,1.029359e+06
50%,2023-05-15 10:38:56,2023-05-16 10:24:42,1.138343e+06,1.213751e+06
75%,2023-05-22 14:28:30,2023-05-23 21:37:16,1.317869e+06,1.405678e+06
max,2024-05-09 09:21:47,2024-05-09 09:21:47,1.583731e+06,1.583732e+06
std,NaN,NaN,2.019547e+05,2.143486e+05

In [ ]:
# created_at이 updated_at보다 더 나중인(큰) 경우를 필터링
invalid_rows = df_friendrequest[df_friendrequest['created_at'] > df_friendrequest['updated_at']]

print(f"이상치 행 개수: {len(invalid_rows)}개")

# 이상치가 존재한다면 상위 데이터 확인
if len(invalid_rows) > 0:
    print(invalid_rows.head())

이상치 행 개수: 0개

In [ ]:
# df_payment 이상치 확인
df_contacts.describe()

       contacts_count
count     5063.000000
mean        25.986174
std         13.601434
min          0.000000
25%         16.000000
50%         24.000000
75%         34.000000
max        114.000000

In [ ]:
# df_payment 이상치 확인
df_payment.describe()

                       created_at
count                       95140
mean   2023-05-27 21:47:32.003741
min           2023-05-13 21:28:34
25%    2023-05-16 11:48:44.750000
50%    2023-05-21 12:40:45.500000
75%    2023-05-27 13:02:52.250000
max           2024-05-08 14:12:45